name: "check-in-hub"
services:
  cih-postgres:
    container_name: cih-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cih-postgres-data:/var/lib/postgresql/data
    ports:
      - "8295:5432"
    networks:
      - cih-net

  cs-check-in-hub:
    container_name: check-in-hub
    image: scobca/check-in-hub:latest
    restart: always
    ports:
      - "8287:8087"
    volumes:
      - cih-data:/var/
    env_file:
      - ./.env
    networks:
      - cih-net

volumes:
  cih-postgres-data:
  cih-data:

networks:
  cih-net:
    driver: bridge